---
{{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.name" $scope }}-hpa
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.name" $scope }}
  minReplicas: {{ $values.hpa.minReplicas }}
  maxReplicas: {{ $values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ $values.hpa.targetCPU }}
