---
  {{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
{{- $rbac := $values.rbac }}
{{- if and $rbac.enabled $values.serviceAccount.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{- if eq $rbac.type "cluster" }}{{- print 'ClusterRole' }}{{- else }}{{ print 'Role' }}{{- end }}
metadata:
  name: {{ $rbac.ref }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}   
rules:
- apiGroups: 
  - ""
  resources: 
  - "secrets"
  - "configmaps"
  - "services"
  verbs: 
  - 'get'
  - 'watch'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{- if eq $rbac.type "cluster" }}{{- print 'ClusterRoleBinding' }}{{- else }}{{ print 'RoleBinding' }}{{- end }}
metadata:
  name: {{ $rbac.ref }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}   
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{- if eq $rbac.type "cluster" }}{{- print 'ClusterRole' }}{{- else }}{{ print 'Role' }}{{- end }}
  name: {{ $rbac.ref }}
subjects:
  - kind: ServiceAccount
    name: {{ $rbac.serviceAccount }}
    namespace: {{ $release.Namespace }}
{{- end }}