{{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
{{- if $values.secrets }}
  {{- range $secret := $values.secrets }}
---
apiVersion: v1
data:
    {{- if $secret.data }}
      {{- range $data := $secret.data }}
  {{ $data.name }}: {{ $data.value | b64enc }}
      {{- end }}
    {{- end }}
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
  {{- end }}
{{- end }}