{{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
{{- if $values.trafficManagement }}
  # External Rules
  {{- if $values.trafficManagement.external }}
    {{- if $values.trafficManagement.external.httpToHttps }}
      {{- range $service := $values.trafficManagement.external.httpToHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-ext
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ $service.host }}
  subsets:
  - name: {{ $service.name }}-tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: {{ default $service.port.https 443 }}
        tls:
          mode: SIMPLE
      {{- end }}
    {{- end }}
  {{- end }}
  # Egress Rules
  {{- if $values.trafficManagement.egress }}
    {{- if $values.trafficManagement.egress.http }}
      {{- range $service := $values.trafficManagement.egress.http }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ default $service.gateway.name "istio-egressgateway" }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ $service.name }}-subset
      {{- end }}
    {{- end }}
    {{- if $values.trafficManagement.egress.https }}
      {{- range $service := $values.trafficManagement.egress.https }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ default $service.gateway.name "istio-egressgateway" }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ $service.name }}-subset
      {{- end }}
    {{- end }}
    {{- if $values.trafficManagement.egress.httpToHttps }}
      {{- range $service := $values.trafficManagement.egress.httpToHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ default $service.gateway.name "istio-egressgateway" }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ $service.name }}-subset
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress-orig
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ $service.host }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: {{ $service.port.https }}
      tls:
        mode: SIMPLE
      {{- end }}
    {{- end }}
    {{- if $values.trafficManagement.egress.tcp }}
      {{- range $service := $values.trafficManagement.egress.tcp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress-tcp
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ default $service.gateway.name "istio-egressgateway" }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ $service.name }}-sub
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: {{ $service.port }}
        tls:
          mode: ISTIO_MUTUAL
          sni: {{ $service.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}-egress
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
  host: {{ $service.host }}
      {{- end }}
    {{- end }}
  {{- end }}
  # Extra Destination Rules
  {{- if $values.trafficManagement.extraDestinationRules }}
    {{- range $service := $values.trafficManagement.extraDestinationRules }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $service.name }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
spec:
{{ toYaml $service.spec | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}