{{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
# External Rules
{{- if $values.external }}
  {{- if $values.external.http }}
    {{- range $service := $values.external.http }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-ext
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port 80 }}
    name: http-port
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
    {{- end }}
  {{- end }}
  {{- if $values.external.https }}
    {{- range $service := $values.external.https }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-ext
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port 443 }}
    name: https-port
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
    {{- end }}
  {{- end }}
  {{- if $values.external.httpAndHttps }}
    {{- range $service := $values.external.httpAndHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-ext
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port.http 80 }}
    name: http-port
    protocol: HTTP
    - number: {{ default $service.port.https 443 }}
    name: https-port
    protocol: HTTPS
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.external.httpToHttps }}
    {{- range $service := $values.external.httpToHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-ext
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port.http 80 }}
    name: http-port
    protocol: HTTP
    - number: {{ default $service.port.https 443 }}
    name: https-port
    protocol: HTTPS
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.external.tcp }}
    {{- range $service := $values.external.tcp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-ext
spec:
  hosts:
  - {{ $service.host }}
  addresses:
  - {{ $service.ip }}/32
  ports:
  - number: {{ $service.port }}
    name: tcp-port
    protocol: TCP
  location: MESH_EXTERNAL
    {{- end }}
  {{- end }}
{{- end }}
# Egress Rules
{{- if $values.egress }}
  {{- if $values.egress.http }}
    {{- range $service := $values.egress.http }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-egress
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port 80 }}
    name: http-port
    protocol: HTTP
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.egress.https }}
    {{- range $service := $values.egress.https }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-egress
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port 443 }}
    name: tls-port
    protocol: TLS
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.egress.httpToHttps }}
    {{- range $service := $values.egress.httpToHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-egress
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port.http 80 }}
    name: http-port
    protocol: HTTP
    - number: {{ default $service.port.https 443 }}
    name: https-port
    protocol: HTTPS
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.egress.httpToHttps }}
    {{- range $service := $values.egress.httpToHttps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-egress
spec:
  hosts:
  - {{ $service.host }}
  ports:
  - number: {{ default $service.port.http 80 }}
    name: http-port
    protocol: HTTP
    - number: {{ default $service.port.https 443 }}
    name: https-port
    protocol: HTTPS
  resolution: DNS
    {{- end }}
  {{- end }}
  {{- if $values.egress.tcp }}
    {{- range $service := $values.egress.tcp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $service.name }}-egress
spec:
  hosts:
  - {{ $service.host }}
  addresses:
  - {{ $service.ip }}/32
  ports:
  - number: {{ $service.port }}
    name: tcp-port
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: {{ $service.ip }}
    {{- end }}
  {{- end }}
{{- end }}