---
{{- $scope := . }}
{{- $values := .Values }}
{{- $release := .Release }}
{{- $chart := .Chart }}
{{- $rbac := $values.rbac }}
{{- if and $rbac.enabled $values.serviceAccount.name }}
{{- if eq $rbac.type "cluster" }}
{{- $role := "ClusterRole" }}
{{- $binding := "ClusterRoleBinding" }}
{{- else }}
{{- $role := "Role" }}
{{- $binding := "RoleBinding" }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "rbac.roleType" $rbac.type }}
metadata:
  name: {{ include "chart.name" $scope }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespace"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "rbac.bindingType" $rbac.type }}
metadata:
  name: {{ include "chart.name" $scope }}
  namespace: {{ $release.Namespace }}
  labels:
{{ include "chart.labels" $scope | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "rbac.roleType" $rbac.type }}
  name: {{ include "chart.name" $scope }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.serviceAccountName" $scope }}
    namespace: {{ $release.Namespace }}
{{- end }}