---
version: v1  # service version, good practice to label every k8s resource with a version if we want to use istio traffic routing capabilities in the future

nameOverride: "fluent-bit"  # replace this by your service name
fullnameOverride: ""  # fill if you whish to override the generatedChartFullName
name: &nameOverride

# Controls if prometheus scrapping should be enabled for this service
prometheus:
  enabled: true  # enables/disable scraping of prometheus metrics
  path: "/api/v1/metrics/prometheus"  # path for scrapping prometheus metrics
  port: 2020  # port were the metrics web server is running
  scheme: "tcp"  # tcp connection scheme

# Service serviceAccount
serviceAccount:
  create: true  # if true the chart will create the service account
  name: fluent-bit  # name of the serviceAccount to use or to create
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

# controls k8s Role Based Access Control settings tied to the serviceAccount
rbac:
  enabled: true  # enables/disables the creation of Role Based Policies
  type: cluster  # type can be cluster or namespace  ( ClusterRole or Role)

# pod affinity policies
affinity: {}

# node selector
nodeSelector: {}

# tolerations
tolerations: []

# service image
image:
  registry: docker.io  # container registry url
  repository: amazon/aws-for-fluent-bit  # container registry repo name
  tag: 2.3.0  # image tag
  pullPolicy: Always  # kubernetes container image pull policy

# limits the container resources
resources:
  # resources that the container requires to boot
  requests:
    memory: 500m
    cpu: 100Mi
  # limit of resources that a container may consume
  limits:
    memory: 500Mi

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# specify k8s configmaps to create
configMaps:
  - name: "fluent-bit-config"  # https://aws.amazon.com/blogs/containers/kubernetes-logging-powered-by-aws-for-fluent-bit/
    data:
      fluent-bit.conf: |
        [SERVICE]
            Parsers_File /fluent-bit/parsers/parsers.conf

        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/*.log
            DB                /var/log/flb_kube.db
            Parser            docker
            Docker_Mode       On
            Mem_Buf_Limit     5MB
            Skip_Long_Lines   On
            Refresh_Interval  10

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc.cluster.local:443
            Merge_Log           On
            Merge_Log_Key       data
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On

        [OUTPUT]
            Name cloudwatch
            Match   **
            region us-east-2
            log_group_name fluentbit-cloudwatch-example
            log_stream_prefix fluentbit-
            auto_create_group true
