name: Release Charts

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm-check
        uses: chemistrygroup/helm-check-action@0.1.6
        env:
          CHART_DIRECTORY: ./charts
  release:
    name: Release
    if: github.ref == 'refs/heads/master'    
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        with:
          charts_repo_url: https://chemistry.github.io/helm-charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"