name: Test

on: 
  push:

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm-check
        uses: chemistrygroup/helm-check-action@0.1.6
        env:
          CHART_DIRECTORY: ./charts